# PUT http://localhost:7070/api/users/reset/627d3d2f1e9aef030533d154
# Content-Type: application/json

# {   
#     "email":"kuranchieracheal@gmail.com",
#     "password":"racheal2020",
#     "newpassword": "racheal4040"
# }


# POST http://localhost:7070/api/users/signup
# Content-Type: application/json

# {   
#     "username": "racheal",
#     "email":"kuranchieracheal@gmail.com",
#     "password":"racheal2023"  
# }

POST http://localhost:7070/api/users/login
Content-Type: application/json

{   
    "email":"kuranchieracheal@gmail.com",
    "password":"racheal2023"  
}

#GET http://localhost:7070/api/users/verify-email/628a3d44e029f099dfe61182/f88cdbadc5de35e3090ef878072809fa


# 6279342dcb54adc6ab4c9c5e
#6279218dfed4ae8c45898d13

#'$2b$10$nWuJyvw8tf4PD27E0xNxY.GtEJ6R/otjBGGoJ7c5u.YtihK4JoE7W',